services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
    restart: always

  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./question-service/.env
    restart: always

  matching-service:
    build:
      context: ./matching-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./matching-service/.env
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  collab-service:
    build:
      context: ./collab-service
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
      - "3003:3003"
    env_file:
      - ./collab-service/.env
    restart: always

networks:
  my-network:
    driver: bridge
