services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env

  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./question-service/.env

