name: Setup Runner Dependencies
description: "Install dependencies for the runner"

runs:   
  using: "composite"
  steps:
    - name: Sudo apt update and upgrade
      shell: bash
      run: |
        sudo apt update
        sudo apt upgrade -y
    - name: Install SOPS
      shell: bash
      run: |
        # https://github.com/getsops/sops/releases
        curl -LO https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
        mv sops-v3.9.0.linux.amd64 /usr/local/bin/sops
        chmod +x /usr/local/bin/sops
    - name: Install age
      shell: bash
      run: sudo apt install -y age
    - name: Install OpenTofu
      shell: bash
      run: |
        # https://opentofu.org/docs/intro/install/deb/
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method deb
        rm -f install-opentofu.sh
    - name: Install gcloud
      shell: bash
      run: |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
        tar -xf google-cloud-cli-linux-x86_64.tar.gz
        ./google-cloud-sdk/install.sh -q
