# This is a basic workflow to help you get started with Actions

name: Actions on Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: kimyongbeom/peerprep-actions-runner:latest
      env:
        AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      options: --privileged


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # https://github.com/actions/checkout/issues/1169
      - run: git config --global --add safe.directory "$PWD"

    # We don't use this, for now.
    #   - name: Find Changed Files
    #     uses: dorny/paths-filter@v3
    #     id: changes
    #     with:
    #       filters: |
    #         global_infra:
    #           - 'tf/**'
    #         frontend:
    #           - 'frontend/**'
    #         backend:
    #           - 'backend/**'
      - name: Decrypt Secret Files
        shell: bash
        run: |
          mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/sops/age
          echo $AGE_SECRET_KEY > ${XDG_CONFIG_HOME:-$HOME/.config}/sops/age/keys.txt
          /bin/bash ./scripts/secret.sh decrypt

      - name: Authenticate to Google Cloud
        shell: bash
        run: make gcloud_auth

      - name: Deploy Global Infrastructure
        shell: bash
        run: make deploy_infra
    
      - name: Deploy Backend
        shell: bash
        run: cd backend && make deploy
    
      - name: Deploy Frontend
        shell: bash
        run: . $NVM_DIR/nvm.sh && cd frontend && make deploy

